class Pet < Struct
  id: Integer
  name: String
  tag: String
end

class Pets < Struct
  attr_reader :pets, type: Array[Pet]
end

class Error < Struct
  code: Integer
  message: String
end

class GetPets200Response < Pets
end

class PostPetsRequestBody < Struct
  id: Integer
  name: String
  tag: String
end

class GetPetsPetId200Response < Pet
end

