class Pet
  def id: () -> Integer
  def name: () -> String
  def tag: () -> String
end

class Pets
  def pets: () -> Array[Pet]
end

class Error
  def code: () -> Integer
  def message: () -> String
end

class GetPets200Response < Pets
end

class PostPetsRequestBody
  def id: () -> Integer
  def name: () -> String
  def tag: () -> String
end

class GetPetsPetId200Response < Pet
end

